# Generated by Django 4.2.7 on 2023-11-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=100)),
                ("src", models.CharField(max_length=256)),
                ("src_url", models.URLField()),
                ("img_src_url", models.URLField()),
                ("headline", models.TextField()),
                ("summary", models.TextField()),
                ("publish_time", models.DateTimeField()),
            ],
        ),
    ]
