# Generated by Django 4.2.7 on 2023-12-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_ticker_news_sentiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="ticker",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="news",
            unique_together={("symbol", "headline")},
        ),
    ]
