# Generated by Django 4.2.7 on 2023-12-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_ticker_ticker_alter_news_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="img_src_url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="news",
            name="src_url",
            field=models.URLField(max_length=500),
        ),
    ]
