# Generated by Django 4.2.7 on 2023-12-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="neutral_news",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
