# Generated by Django 4.2.7 on 2023-12-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_analysis_neutral_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="img_src_url",
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="news",
            name="sentiment",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="src",
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="news",
            name="src_url",
            field=models.URLField(max_length=2048),
        ),
    ]
