# Generated by Django 4.2.7 on 2023-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_alter_news_img_src_url_alter_news_sentiment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="need_attention",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="news",
            name="reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="sentiment",
            field=models.IntegerField(default=0),
        ),
    ]
