environment: "prod"

gcp:
  project: folio-feed-403709
  location: us-central1

backend:
  image:
    registry: us-central1-docker.pkg.dev/folio-feed-403709/image-registry
    repository: folio-feed-backend
    tag: &backendImageTag e379f606b0d7535f97f79eb130ce6cbdb92a93c4

  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3

  nodeSelector:
    cloud.google.com/gke-spot: "true"
    cloud.google.com/compute-class: Scale-Out

  resources:
    # GKE Autopilot only considers requests. limits are same as requests.
    requests:
      cpu: 250m
      memory: 512Mi


frontend:
  image:
    registry: us-central1-docker.pkg.dev/folio-feed-403709/image-registry
    repository: folio-feed-frontend
    tag: &frontendImageTag ea14134181209883af6d997a2a107936a7663323

  replicaCount: 1
  autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3

  nodeSelector:
    cloud.google.com/gke-spot: "true"
    cloud.google.com/compute-class: Scale-Out

  resources:
    # GKE Autopilot only considers requests. limits are same as requests.
    requests:
      cpu: 250m
      memory: 512Mi

fetcher:
  image:
    registry: us-central1-docker.pkg.dev/folio-feed-403709/image-registry
    repository: folio-feed-fetcher
    tag: &fetcherImageTag 34467c1a88fd808abcd01fb1ff5b6ea74535637d


analyzer:
  image:
    registry: us-central1-docker.pkg.dev/folio-feed-403709/image-registry
    repository: folio-feed-analyzer
    tag: &analyzerImageTag 0a21a516a2177fadf7f113670928800d96f92d33
  modelName: "text-bison"




rabbitmq:
  replicaCount: 1
  persistence:
    storageClass: "standard-rwo"
    size: 5Gi
  nodeSelector:
    cloud.google.com/gke-spot: "true"

postgresql:
  global:
    storageClass: premium-rwo
    postgresql:
      auth:
        username: postgres
        existingSecret: postgresql-password
        database: folio-feed

  primary:
    resources:
      cpu: 250m
      memory: 512Mi
    persistence:
      size: 10Gi

    nodeSelector:
        cloud.google.com/gke-spot: "true"
