environment: "prod"

gcp:
  project: folio-feed-403709
  location: us-central1

backend:
  image:
    registry: us-central1-docker.pkg.dev/folio-feed-403709/image-registry
    repository: folio-feed-backend
    tag: &backendImageTag 4a1f09a0202c27fdaa7818cbbd3cc76b607783dd

  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3

  nodeSelector:
    cloud.google.com/gke-spot: "true"
    cloud.google.com/compute-class: Scale-Out

  resources:
    # GKE Autopilot only considers requests. limits are same as requests.
    requests:
      cpu: 250m
      memory: 512Mi


frontend:
  image:
    registry: us-central1-docker.pkg.dev/folio-feed-403709/image-registry
    repository: folio-feed-frontend
    tag: &frontendImageTag aac17e42ad16314b40dca22cffbf6ac76457adb4

  replicaCount: 1
  autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3

  nodeSelector:
    cloud.google.com/gke-spot: "true"
    cloud.google.com/compute-class: Scale-Out

  resources:
    # GKE Autopilot only considers requests. limits are same as requests.
    requests:
      cpu: 250m
      memory: 512Mi

fetcher:
  image:
    registry: us-central1-docker.pkg.dev/folio-feed-403709/image-registry
    repository: folio-feed-fetcher
    tag: &fetcherImageTag 4bd0eb6d467033ebfe50555b88b3b7c0a49909a0

  nodeSelector:
    cloud.google.com/gke-spot: "true"
    cloud.google.com/compute-class: Scale-Out

  resources:
    # GKE Autopilot only considers requests. limits are same as requests.
    requests:
      cpu: 250m
      memory: 512Mi


analyzer:
  image:
    registry: us-central1-docker.pkg.dev/folio-feed-403709/image-registry
    repository: folio-feed-analyzer
    tag: &analyzerImageTag 0a21a516a2177fadf7f113670928800d96f92d33
  modelName: "text-bison"

  nodeSelector:
    cloud.google.com/gke-spot: "true"
    cloud.google.com/compute-class: Scale-Out

  resources:
    # GKE Autopilot only considers requests. limits are same as requests.
    requests:
      cpu: 250m
      memory: 512Mi




rabbitmq:
  namespaceOverride: "rabbitmq"
  replicaCount: 1
  persistence:
    storageClass: "premium-rwo"
    size: 5Gi
  nodeSelector:
    cloud.google.com/gke-spot: "true"
    cloud.google.com/compute-class: Scale-Out
  auth:
    username: user
    existingPasswordSecret: folio-feed-rabbitmq
    existingErlangCookieSecret: folio-feed-rabbitmq
  resources:
    # GKE Autopilot only considers requests. limits are same as requests.
    requests:
      cpu: 250m
      memory: 512Mi

postgresql:
  global:
    storageClass: premium-rwo
    postgresql:
      auth:
        username: postgres
        existingSecret: postgresql-password
        database: folio-feed

  primary:
    resources:
      cpu: 250m
      memory: 512Mi
    persistence:
      size: 10Gi

    nodeSelector:
      cloud.google.com/gke-spot: "true"
      cloud.google.com/compute-class: Scale-Out
