environment: "prod"

backend:
  image:
    registry: us-central1-docker.pkg.dev/folio-feed-403709/image-registry
    repository: folio-feed-backend
    tag: &backendImageTag cf71d729c35739f5d3b0ed265688a781ef7e2e85

  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3

  nodeSelector:
    cloud.google.com/gke-spot: "true"

  resources:
    # GKE Autopilot only considers requests. limits are same as requests.
    requests:
      cpu: 250m
      memory: 512Mi


frontend:
  image:
    registry: us-central1-docker.pkg.dev/folio-feed-403709/image-registry
    repository: folio-feed-frontend
    tag: &frontendImageTag 996e8c2a3f83d38dbb24e9217e2d115a2cf43b9f

  replicaCount: 1
  autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3

  nodeSelector:
    cloud.google.com/gke-spot: "true"

  resources:
    # GKE Autopilot only considers requests. limits are same as requests.
    requests:
      cpu: 250m
      memory: 512Mi




rabbitmq:
  replicaCount: 1
  persistence:
    storageClass: "standard-rwo"
    size: 5Gi
  nodeSelector:
    cloud.google.com/gke-spot: "true"

postgresql:
  global:
    storageClass: premium-rwo
    postgresql:
      auth:
        username: postgres
        existingSecret: postgresql-password
        database: folio-feed

  primary:
    resources:
      cpu: 250m
      memory: 512Mi
    persistence:
      size: 10Gi

    nodeSelector:
        cloud.google.com/gke-spot: "true"
