apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "folio-feed.fullname" . }}-analyzer
  labels:
    {{- include "folio-feed.labels" . | nindent 4 }}
    app: fetcher
spec:
  schedule: "50 23 * * *" # every day at 23:30 UTC
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          volumes:
            - name: google-cloud-key
              secret:
                secretName: vertex-ai-key
          containers:
            - name: analyzer
              {{- with .Values.analyzer.image }}
              image: '{{- printf "%s/%s:%s" .registry .repository .tag}}'
              {{- end}}
              command:
                - python
                - analyzer.py
                - analyze
              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
                  readOnly: true
              env:
                - name: DB_HOST
                  value: folio-feed-postgresql.folio-feed.svc.cluster.local
                - name: DB_PORT
                  value: '5432'
                - name: DB_NAME
                  value: "folio-feed"
                - name: DB_USER
                  value: "postgres"
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-password
                      key: postgres-password
                - name: GCP_PROJECT
                  value: {{ .Values.gcp.project }}
                - name: GCP_LOCATION
                  value: {{ .Values.gcp.location }}
                - name: MODEL_NAME
                  value: {{ .Values.analyzer.modelName }}
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/vertex-ai-key.json
          restartPolicy: Never
