apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "folio-feed.fullname" . }}-backend-monitoring
  labels:
    {{- include "folio-feed.labels" . | nindent 4 }}
    app: backend
spec:
  selector:
    matchLabels:
      {{- include "folio-feed.selectorLabels" . | nindent 6 }}
      app: backend
  endpoints:
  - port: http
    interval: 30s