apiVersion: v1
kind: Service
metadata:
  name: {{ include "folio-feed.fullname" . }}-frontend
  labels:
    {{- include "folio-feed.labels" . | nindent 4 }}
    app: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    {{- include "folio-feed.selectorLabels" . | nindent 4 }}
    app: frontend
