name: Build Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "applications/frontend/**"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Run Lint Check
      run: task lint-check

    - name: Run all tests
      run: task test

    # Authentication to GCP via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Docker configuration
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet
      
    - name: Set up Taskfile
      uses: arduino/setup-task@v1.0.3

    - name: Build
      run: task build-frontend-image tag="$GITHUB_SHA"

    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: task push-frontend-image tag="$GITHUB_SHA"

    - name: Replace Frontend Image Tag
      run: sed -i "s/\(&frontendImageTag\) [^[:space:]]*/\1 $GITHUB_SHA/g" infrastructure/k8s/folio-feed-helm/values.yaml

    - name: Commit the Changes
      run: |
        git config user.name "Github Actions"
        git config user.email github-actions@github.com
        git diff
        git add infrastructure/k8s/folio-feed-helm/values.yaml
        git commit -m "frontend image update: $GITHUB_SHA"
        git push origin main
