# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - "applications/*"
  pull_request:
    branches: [ "main" ]
    paths:
      - "applications/*"

permissions:
  contents: read

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Set up Taskfile
      uses: arduino/setup-task@v1.0.3
    - name: Run Lint
      run: task lint-check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Set up Taskfile
      uses: arduino/setup-task@v1.0.3
    - name: Test Backend
      run: task test-backend
    - name: Test Data Fetcher
      run: task test-fetcher
    - name: Test Data Analyzer
      run: task test-analyzer
